apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    @include containers.conf
    @include systemd.conf

  containers.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.pos
      tag kubernetes.*
      format json
    </source>

    <match kubernetes.**>
      @type awslogs
      aws_key_id "#{ENV['AWS_ACCESS_KEY_ID']}"
      aws_sec_key "#{ENV['AWS_SECRET_ACCESS_KEY']}"
      region ap-south-1
      log_group_name fluentd-k3s-logs
      auto_create_stream true
    </match>

  systemd.conf: |
    <source>
      @type systemd
      path /var/log/journal
      tag systemd.*
    </source>

    <match systemd.**>
      @type awslogs
      aws_key_id "#{ENV['AWS_ACCESS_KEY_ID']}"
      aws_sec_key "#{ENV['AWS_SECRET_ACCESS_KEY']}"
      region ap-south-1
      log_group_name fluentd-k3s-systemd
      auto_create_stream true
    </match>
